<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAotCompatible>true</IsAotCompatible>
    <PackageId>Eventa.Adapters</PackageId>
    <AssemblyName>Eventa.Adapters</AssemblyName>
    <RootNamespace>Eventa.Adapters</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Eventa\Eventa.csproj" />
  </ItemGroup>

</Project>
