name: Run Example

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-example:
    name: Run example
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
          cache: true
          cache-dependency-path: |
            examples/Eventa.Example/packages.lock.json
            tests/Eventa.Tests/packages.lock.json

      - name: Restore
        run: dotnet restore Eventa.slnx --locked-mode

      - name: Run example
        run: dotnet run --project examples/Eventa.Example/Eventa.Example.csproj --configuration Release --no-restore
